# -*- coding: utf-8 -*-
"""Qubitrics_Form_Task_2_Text_Extraction_from_image_using_OCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W3QNcaE1KFp0a6B5NZlaX7IzcXNKiOD3

###### <b>Task # 02:</b> 
<h1>Computer Vision(OCR/ICR):</h1>

### Go to https://content.sbigeneral.in/uploads/e1904ff17d084f6582d5cc43bb6e059e.pdf

<ul>
<li>Perform OCR on handwritten text using the above form</li>
<li>Print the given form.</li>
<li>Fill it with handwritten data.</li>
<li>Apply OCR via OpenCV.</li>
</ul>

## <b>Step-1: Installing extra Required Libraries</b>
"""

!apt install tesseract-ocr
!pip install pytesseract

"""## <b>Step-2: Importing required Libraries</b>"""

import os, cv2, shutil, random, pytesseract
import numpy as np
from google.colab import files
from google.colab import drive
import matplotlib.pyplot as plt
try:
 from PIL import Image
except ImportError:
  import Image

"""## <b>Step-3:Mounting Google Drive to access the required files</b>"""

drive.mount('/content/gdrive',force_remount=True)

"""## <b>Step-4: Setting path for Images so that the files can be directly used</b>


"""

#Path in Drive: ./content\gdrive\MyDrive\Qubritics-Form-Ocr-task\Images\1.jpg'
image_path = '/content/gdrive/MyDrive/Qubritics-Form-Ocr-task/images/1_2x.jpg'

"""## <b>Step-6: Accesing image from path & Displaying via __</b> *Plt.Show()*"""

orignal_image_item=cv2.imread(image_path)
plt.imshow(orignal_image_item)
plt.axis("off")
plt.show()

"""## <b>Step-8: Applying Tesseract_OCR Text Extraction on Orignal image</b>"""

extractedInformation = pytesseract.image_to_string(Image.open(image_path))
print(extractedInformation)

"""##### FootNote:
<h5> The system accuracy is lower due to LOW-IMAGE-QUALITY!</h5>
"""